app = 'debian13-ssh'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  ROOT_PASSWORD = 'changeme'
  TZ = 'Etc/UTC'

[[services]]
  protocol = 'tcp'
  internal_port = 22
  
  [[services.ports]]
    port = '22'

[mounts]
  source = 'ssh_data'
  destination = '/root/.ssh'

[scale]
  min_machines_running = 1
